package tisdaleproject2;
/******************************************************
***  Class Name: CarCreatorGUI
***  Class Author: Chris Tisdale 
******************************************************
*** Purpose of the class:
*** This class demonstrates functionality of the Car class. It provides a GUI
*** for the user to enter make, model, and select a color for a car.
*** Then they can click a button to create a car. After a car has been created
*** the accelerate and brake buttons can be used to change the speed. The
*** Get Information button will display the information of the car as many times
*** as the user would like to see the information of the car.
****************************************************** 
*** September 19, 2017
******************************************************
*** August 30:      Reviewed assignment and created design for my program and
***                 implemented with pseudocode.
*** August 31:      Created TisdaleProject2, CarCreaterGui and Car classes.
***                 Tested the input and verified the output of the program, as well as error catching.
*** September 7:    Added comments and final testing.
******************************************************
***  
*******************************************************/
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class CarCreatorGUI extends javax.swing.JFrame {
    // variable declarations support functionality
    Color color;
    ArrayList<Car> cars = new ArrayList<>();
    int carCount = -1;
    public CarCreatorGUI() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInstructions = new javax.swing.JLabel();
        lblMake = new javax.swing.JLabel();
        tfMake = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        lblModel = new javax.swing.JLabel();
        tfModel = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        cbColor = new javax.swing.JComboBox<>();
        lbCarInformation = new javax.swing.JLabel();
        btnGetInformation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCarInformation = new javax.swing.JTextArea();
        btnAccelerate = new javax.swing.JButton();
        btnBrake = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInstructions.setText("Type the make and model in the indicated boxes below, then choose a color and click the create button to create a vehicle.");

        lblMake.setText("Make: ");

        btnCreate.setText("Create Car");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblModel.setText("Model: ");

        lblColor.setText("Color:");

        cbColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "white", "black", "gray", "blue", "red", "green", "yellow", "orange" }));
        cbColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbColorActionPerformed(evt);
            }
        });

        lbCarInformation.setText("Car Information:");

        btnGetInformation.setText("Get Information");
        btnGetInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetInformationActionPerformed(evt);
            }
        });

        taCarInformation.setEditable(false);
        taCarInformation.setColumns(20);
        taCarInformation.setRows(5);
        jScrollPane1.setViewportView(taCarInformation);

        btnAccelerate.setText("Accelerate");
        btnAccelerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccelerateActionPerformed(evt);
            }
        });

        btnBrake.setText("Brake");
        btnBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCarInformation)
                        .addGap(67, 67, 67)
                        .addComponent(btnGetInformation))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMake)
                            .addComponent(lblModel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMake, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnCreate))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblColor)
                        .addGap(18, 18, 18)
                        .addComponent(cbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(210, 210, 210))
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnAccelerate)
                .addGap(18, 18, 18)
                .addComponent(btnBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblInstructions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblInstructions)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMake)
                    .addComponent(tfMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(tfModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(cbColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccelerate)
                    .addComponent(btnBrake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCarInformation)
                    .addComponent(btnGetInformation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/*****************************************************
*** Method Name: btnCreateActionPerformed
*** Author: Chris Tisdale
******************************************************
*** Purpose of the Method: Tries to create a car from the text fields
*** for make and model as well as combo box for color. If any of the information
*** is blank or invalid, it will display an error message dialog.
*** Method Inputs: make and model from text field, color from combo box
*** Return value: void
******************************************************
*** Date: August 31
******************************************************/
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try {
            Car car = new Car(tfMake.getText(), tfModel.getText(), color);
            cars.add(car);
            carCount++;
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: \n" + e + "\nPlease correct this problem and try again.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

/*****************************************************
*** Method Name: cbColorActionPerformed
*** Author: Chris Tisdale
******************************************************
*** Purpose of the Method: Gets the user's selection of color by the
*** position of the color in the combo box. This could easily be changed
*** but is currently sorted by the most popular colors with several added
*** at the end.
*** Method Inputs: color from combo box
*** Return value: void
******************************************************
*** Date: August 31
******************************************************/
    private void cbColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbColorActionPerformed
        if (cbColor.getSelectedIndex() == 1) {
            color = Color.white;
        }
        if (cbColor.getSelectedIndex() == 2) {
            color = Color.black;
        }
        if (cbColor.getSelectedIndex() == 3) {
            color = Color.gray;
        }
        if (cbColor.getSelectedIndex() == 4) {
            color = Color.blue;
        }
        if (cbColor.getSelectedIndex() == 5) {
            color = Color.red;
        }
        if (cbColor.getSelectedIndex() == 6) {
            color = Color.green;
        }
        if (cbColor.getSelectedIndex() == 7) {
            color = Color.yellow;
        }
        if (cbColor.getSelectedIndex() == 8) {
            color = Color.orange;
        }
    }//GEN-LAST:event_cbColorActionPerformed

/*****************************************************
*** Method Name: btnGetInformationActionPerformed
*** Author: Chris Tisdale
******************************************************
*** Purpose of the Method: Tries to display car information for the most recently added car.
*** If no car is added an error message dialog will say this. Otherwise it will print the
*** car number (starting with 1), make, model, java Color class (RGB value), and speed.
*** It can be used after changes in speed to demonstrate that those methods work correctly.
*** Method Inputs: none
*** Return value: void
******************************************************
*** Date: August 31
******************************************************/
    private void btnGetInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetInformationActionPerformed
        if (cars.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: \n"  + "\nThere is no car added yet.", "No Car", JOptionPane.ERROR_MESSAGE);
        } else {
            int tempCarCount = carCount+1;
            taCarInformation.setText(
                
                "Car Number: " + tempCarCount +
                "\nMake: " + cars.get(carCount).getMake() +
                "\nModel: " + cars.get(carCount).getModel() +
                "\nColor RGB values: " +cars.get(carCount).getColor().toString() +
                "\nSpeed: " + cars.get(carCount).getSpeed());
        }
    }//GEN-LAST:event_btnGetInformationActionPerformed

/*****************************************************
*** Method Name: btnAccelerateActionPerformed
*** Author: Chris Tisdale
******************************************************
*** Purpose of the Method: Increments speed of the most recently added
*** car by 5 through calling accelerate method from car class. If no car is
*** added yet an error message dialog will pop up.
*** Method Inputs: none
*** Return value: void
******************************************************
*** Date: August 31
******************************************************/
    private void btnAccelerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccelerateActionPerformed
        if (cars.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: \n"  + "\nThere is no car added yet.", "No Car", JOptionPane.ERROR_MESSAGE);
        } else {
        cars.get(carCount).accelerate();
        }
    }//GEN-LAST:event_btnAccelerateActionPerformed

/*****************************************************
*** Method Name: btnBrakeActionPerformed
*** Author: Chris Tisdale
******************************************************
*** Purpose of the Method: Decrements speed of the most recently added
*** car by 5 through calling brake method from car class. If no car is
*** added yet an error message dialog will pop up.
*** Method Inputs: none
*** Return value: void
******************************************************
*** Date: August 31
******************************************************/
    private void btnBrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrakeActionPerformed
        if (cars.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: \n"  + "\nThere is no car added yet.", "No Car", JOptionPane.ERROR_MESSAGE);
        } else {
        cars.get(carCount).brake();
        }
    }//GEN-LAST:event_btnBrakeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarCreatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarCreatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccelerate;
    private javax.swing.JButton btnBrake;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnGetInformation;
    private javax.swing.JComboBox<String> cbColor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCarInformation;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JTextArea taCarInformation;
    private javax.swing.JTextField tfMake;
    private javax.swing.JTextField tfModel;
    // End of variables declaration//GEN-END:variables
}
